#!/bin/sh

##############################################################################
# Gradle start up script for POSIX generated by Gradle.
#
# Important for running:
#
#     (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#         noncompliant, but you have some other compliant shell such as ksh or
#         bash, then to run this script, type that shell name before the whole
#         command line, like:
#
#         ksh Gradle
#
#         Busybox and similar reduced shells will NOT work, because this script
#         requires all of these POSIX shell features:
#           * functions;
#           * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#             «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#           * compound commands having a testable exit status, especially «case»;
#           * various built-in commands including «command», «set», and «ulimit».
#
#     (2) This script is not useful to run unless your shell is running on a
#         POSIX-compliant OS with a POSIX-compliant version of basic commands
#         like basename, cat, cd, chmod, cp, mkdir, mv, printf, pwd, rm, and test.
#
##############################################################################

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" -a "$darwin" = "false" -a "$nonstop" = "false" ] ; then
    MAX_FD_LIMIT=$(ulimit -H -n)
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

exec "$JAVACMD" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
